### ISSUE TITLE
Pyinstaller missing import

### ISSUE THREAD

**Issue by pirumpi** [miguelgrinberg/flask-sock#8]
It seems that an import is missing when I try to create a binary using pyinstaller

```bash
Traceback (most recent call last):
  File "flask\app.py", line 2070, in wsgi_app
  File "flask\app.py", line 1515, in full_dispatch_request
  File "flask_cors\extension.py", line 165, in wrapped_function
  File "flask\app.py", line 1513, in full_dispatch_request
  File "flask\app.py", line 1499, in dispatch_request
  File "flask_sock\__init__.py", line 24, in websocket_route
  File "simple_websocket\ws.py", line 136, in __init__
AttributeError: 'Input' object has no attribute 'raw'
```

The application runs great otherwise. Have you tried creating a binary using flask_sock or simple_socket? if so, how did you overcome this issue?

**Comment by miguelgrinberg** [comment]
What Python version is this?

**Comment by pirumpi** [comment]
Python 3.7.10
